### ISSUE TITLE
SLC usage of [sys.ui.concept] editor  ←(spike)

### ISSUE THREAD

**Issue by philcockfield** [cellplatform/platform-0.2.0#153]
[tdb.slc.ember.slugs.xlsx](https://github.com/cellplatform/platform-0.2.0/files/12272661/tdb.slc.ember.slugs.xlsx)

[workshop-1.zip](https://github.com/cellplatform/platform-0.2.0/files/12272805/workshop-1.zip)
[workshop-2.zip](https://github.com/cellplatform/platform-0.2.0/files/12272810/workshop-2.zip)
[workshop-3.zip](https://github.com/cellplatform/platform-0.2.0/files/12272811/workshop-3.zip)

**Comment by philcockfield** [comment]
<img width="438" alt="image" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/3d494c3d-82ff-4559-b906-36021b2c1d83">

**Comment by philcockfield** [comment]
![image](https://github.com/cellplatform/platform-0.2.0/assets/185555/c75e78cf-a0e5-443d-888a-7fbe1682b868)

**Comment by philcockfield** [comment]
![image](https://github.com/cellplatform/platform-0.2.0/assets/185555/90756274-3664-4670-b80b-48057c1b8c71)

**Comment by philcockfield** [comment]
intro

<img width="825" alt="image" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/81ef82e9-c2c0-4d59-a0e4-806c3a889cca">

-----

<img width="814" alt="image" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/7d33d06e-6adc-417b-84df-f98f35b1e64f">

---

<img width="768" alt="image" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/ca448cab-383c-4170-80ba-d55e3c83a312">

**Comment by philcockfield** [comment]
<img width="768" alt="image" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/ca448cab-383c-4170-80ba-d55e3c83a312">

**Comment by philcockfield** [comment]
intro.programme

<img width="787" alt="image" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/788b5fda-85af-447c-8651-ce8b1030eda3">

---

<img width="757" alt="image" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/576b41d7-dfa8-4b3f-9960-7bedbb188d54">

----

<img width="1392" alt="image" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/d1314e2f-ed07-4ec1-a746-457cfe2ccff8">

**Comment by philcockfield** [comment]
intro.canvas

0, 45
![intro canvas 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/724e767c-560e-46fc-9868-ec9763cbb6b7)

---

14
![intro canvas 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/c35bbfd9-e1a4-4974-bcf1-be970365b69d)

---

21
![intro canvas 3](https://github.com/cellplatform/platform-0.2.0/assets/185555/93447543-e794-42da-95e4-e47d5d1aa4ad)

**Comment by philcockfield** [comment]
purpose

![purpose](https://github.com/cellplatform/platform-0.2.0/assets/185555/1f72bdfd-2c67-4286-aac8-b489204ba79e)

**Comment by philcockfield** [comment]
customermodel.overview


0s
![Overview](https://github.com/cellplatform/platform-0.2.0/assets/185555/11f11af7-d993-4e81-bac6-d88fdcd315ad)

10s
![model Customers](https://github.com/cellplatform/platform-0.2.0/assets/185555/95af98f0-e9b0-470f-b3df-d67075b79369)

**Comment by philcockfield** [comment]
customermodel.customers.1
customermodel.customers.2
customermodel.customers.earlyadopters

![model Customers](https://github.com/cellplatform/platform-0.2.0/assets/185555/72027c74-17f4-450c-806f-d4aeae158931)

**Comment by philcockfield** [comment]
customermodel.jobs
customermodel.jobs.existingalternatives


![model Jobs](https://github.com/cellplatform/platform-0.2.0/assets/185555/f1f61d51-9803-4928-bbe5-790153e578eb)

**Comment by philcockfield** [comment]
customermodel.uvp

![model UVP](https://github.com/cellplatform/platform-0.2.0/assets/185555/83301cb2-c07b-44a5-9178-0485f3679b8a)

**Comment by philcockfield** [comment]
customermodel.solution

![model Solution](https://github.com/cellplatform/platform-0.2.0/assets/185555/5920e11b-331c-4158-87d4-b8bb8af5516b)

**Comment by philcockfield** [comment]
customermodel.example.FB.intro
customermodel.example.FB.customers

---
0s
![customermodel example FB customers 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/9c1fd4ba-4727-41b0-9ce7-5407debed3c0)

8s
![customermodel example FB customers 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/347fbf6d-ad69-4157-855f-7457b38f8cc1)

35s
![customermodel example FB customers 3](https://github.com/cellplatform/platform-0.2.0/assets/185555/88d5ac08-5788-4734-8e46-78bf5b931f13)

----

customermodel.example.FB.jobs

0s
![CustomerModel Example FB Jobs 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/71eb6113-1541-48ae-b094-1f262fac6ac7)

5s
![CustomerModel Example FB Jobs 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/e19aabbb-d9e1-4260-8cd0-0e483b52a2e4)


---

customermodel.example.FB.UVP

0s
![CustomerModel Example FB UVP 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/19b6d32a-f225-4802-8b2c-2665c929fe46)

5s
![CustomerModel Example FB UVP 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/4d84be14-65c9-4d7e-a49f-eb81657f2e45)


---

customermodel.example.FB.solution

0s
![CustomerModel Example FB Solution 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/7e690b29-77d4-47f1-bc9f-65cef6f4860b)

17s
![CustomerModel Example FB Solution 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/1e92ad06-cfd1-4eb1-b9cb-6d740485a09a)



----
customermodel.example.FB.conclusion

![CustomerModel Example FB Conclusion](https://github.com/cellplatform/platform-0.2.0/assets/185555/92bb4005-ff1d-4654-85f3-b51feedebdeb)

**Comment by rowanyeoman** [comment]
![image](https://github.com/cellplatform/platform-0.2.0/assets/17206794/4c6cf8b1-d64e-4108-a635-c37d0cc4bd33)

**Comment by rowanyeoman** [comment]
![image](https://github.com/cellplatform/platform-0.2.0/assets/17206794/acb085c3-48a6-4519-8e01-ca5e88fcbb1d)

**Comment by rowanyeoman** [comment]
![image](https://github.com/cellplatform/platform-0.2.0/assets/17206794/c846cb41-3305-412c-9956-8c6fb79cdb61)

**Comment by philcockfield** [comment]
impactmodel.overview

0s
![Overview 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/72156ccf-9cf7-404c-9251-9e6ca40cb646)

15s
![Overview 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/16ad8903-e263-4f5b-b7d2-7604fcadbe70)

**Comment by philcockfield** [comment]
impactmodel.overview.context
impactmodel.overview.disclaimer

![Overview 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/e5282930-acbd-44f5-ae4c-b787da4a4202)

**Comment by philcockfield** [comment]
impactmodel.issue

![issue](https://github.com/cellplatform/platform-0.2.0/assets/185555/76d6631a-78a0-47b1-8743-f6d19382a2ce)

**Comment by philcockfield** [comment]
impactmodel.participants

![impactmodel example participants](https://github.com/cellplatform/platform-0.2.0/assets/185555/ef25251c-b135-41f9-9fe9-520c9383ae30)

**Comment by philcockfield** [comment]
impactmodel.activities

![activities](https://github.com/cellplatform/platform-0.2.0/assets/185555/35f87ff3-f808-4c3b-9ce2-46b24f061ce1)

**Comment by philcockfield** [comment]
impactmodel.shorttermoutcomes
![short-term-outcomes](https://github.com/cellplatform/platform-0.2.0/assets/185555/dc5670e3-d1c9-45dc-ad2d-845e7dcd51e9)

**Comment by philcockfield** [comment]
impactmodel.mediumtermoutcomes

# 🐷
![medium-term-outcomes](https://github.com/cellplatform/platform-0.2.0/assets/185555/32d9afc4-6f62-483f-b0ef-41dd1f838d84)

**Comment by philcockfield** [comment]
impactmodel.longtermoutcomes

![long-term-outcomes](https://github.com/cellplatform/platform-0.2.0/assets/185555/74900d97-7d28-4729-817b-686ef9932db3)

**Comment by philcockfield** [comment]
impactmodel.impact

![impact](https://github.com/cellplatform/platform-0.2.0/assets/185555/a2649ae6-1205-425c-b082-b3e0d4d9335d)

**Comment by rowanyeoman** [comment]
> customermodel.overview
> 
> # ?? 🐷
> ![Overview](https://user-images.githubusercontent.com/185555/258682259-b481d8f2-3d4c-4bc5-a981-f9d20de2a007.png)

Yep, these 2 are the correct ones for the customermodel.overview video

**Comment by philcockfield** [comment]
impactmodel.example.intro

![ImpactModel Example Intro](https://github.com/cellplatform/platform-0.2.0/assets/185555/1ad84605-ef8a-4d46-b2a9-8e96b1f4c9b1)

---

impactmodel.example.issue
![ImpactModel Example Issue](https://github.com/cellplatform/platform-0.2.0/assets/185555/54af1d7e-1198-40e4-a524-5a4d051351c0)

---

impactmodel.example.participants
![ImpactModel Example Participants](https://github.com/cellplatform/platform-0.2.0/assets/185555/2651e155-e1c2-484b-aa9b-6783971180f9)



----

impactmodel.example.activities
![ImpactModel Example Activities](https://github.com/cellplatform/platform-0.2.0/assets/185555/ed1df6d6-4b79-48bd-b0c7-ff37b4fab1bb)

---

impactmodel.example.shorttermoutcomes
![ImpactModel Example ShortTermOutcomes](https://github.com/cellplatform/platform-0.2.0/assets/185555/108503dd-d81b-495e-b750-66bf68709120)

---

impactmodel.example.mediumtermoutcomes
![ImpactModel Example MediumTermOutcomes](https://github.com/cellplatform/platform-0.2.0/assets/185555/0eacf674-633d-42e7-943c-713fcfb668fb)


----

impactmodel.example.longtermoutcomes
![ImpactModel Example LongTermOutcomes](https://github.com/cellplatform/platform-0.2.0/assets/185555/77673802-b620-4869-bc95-9c18c769125d)


---

impactmodel.example.impact
![ImpactModel Example Impact](https://github.com/cellplatform/platform-0.2.0/assets/185555/01e41c37-65f6-4db2-8b46-2882a0bf094c)

**Comment by philcockfield** [comment]
economicmodel.overview

0s
![Overview 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/65aa349d-430a-4870-ae58-4a1635848511)


18s
![Overview 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/37d60998-478d-4709-8c73-a736e22e36b1)

**Comment by philcockfield** [comment]
economicmodel.channels

![channels](https://github.com/cellplatform/platform-0.2.0/assets/185555/df1da57d-f508-41d8-964a-c8537e0c6a91)

**Comment by philcockfield** [comment]
economicmodel.channels

![channels](https://github.com/cellplatform/platform-0.2.0/assets/185555/df1da57d-f508-41d8-964a-c8537e0c6a91)

---

economicmodel.financialmodel.intro
![financial](https://github.com/cellplatform/platform-0.2.0/assets/185555/ead93fa0-83a9-4586-bb18-9b51c13690c5)

---

economicmodel.financialmodel.revenue
![revenue](https://github.com/cellplatform/platform-0.2.0/assets/185555/0fc5bd70-2cbf-4a56-98cc-f8fd0c63d38e)

---

economicmodel.financialmodel.costs
![costs](https://github.com/cellplatform/platform-0.2.0/assets/185555/0fe80d38-db0d-43d3-ab6a-507108e57869)

---

economicmodel.advantage.1leverage
economicmodel.advantage.2innovate

![advantage](https://github.com/cellplatform/platform-0.2.0/assets/185555/af0c5f15-b019-4a45-8a02-2960899387db)

**Comment by philcockfield** [comment]
economicmodel.FB.example.overview

![EconomicModel FB Example Overview](https://github.com/cellplatform/platform-0.2.0/assets/185555/bc064632-7492-4f1e-b333-4d111af63126)

**Comment by philcockfield** [comment]
economicmodel.FB.example.channels

0s
![EconomicModel FB Example Channels 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/3e8b3437-2964-4427-b750-11d1ee4110e3)

6s
![EconomicModel FB Example Channels 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/ad0e2ad1-c5cf-4921-a830-bb97810fbe72)

**Comment by philcockfield** [comment]
economicmodel.FB.example.financialmodel

0S
![EconomicModel FB Example FinancailModel 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/b45f3292-fee0-4305-8574-8cd838e7d86a)

6S
![EconomicModel FB Example FinancailModel 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/b3c8b9c2-50b0-4538-9d1e-7301dfe44e4f)

25s
![EconomicModel FB Example FinancailModel 3](https://github.com/cellplatform/platform-0.2.0/assets/185555/2f342a99-2b5b-4b88-8544-aba3234000c6)

**Comment by philcockfield** [comment]
economicmodel.FB.example.advantage

0s
![EconomicModel FB Example Advantage 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/cc2c78dc-8f66-4dd7-9f25-ba503f040a6c)

14s
![EconomicModel FB Example Advantage 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/53af8ba0-9955-4299-a5d6-1b73edaeafce)

**Comment by philcockfield** [comment]
metrics.keymetrics

![key-metrics](https://github.com/cellplatform/platform-0.2.0/assets/185555/9d2e7906-3079-4299-8ffe-546caf77f941)

**Comment by philcockfield** [comment]
canvas.conclusion

<img width="787" alt="image" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/788b5fda-85af-447c-8651-ce8b1030eda3">

**Comment by philcockfield** [comment]
strategy.intro
strategy.intro.2

0s
<img width="757" alt="image" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/576b41d7-dfa8-4b3f-9960-7bedbb188d54">

---

strategy.intro.2

54s
<img width="1240" alt="strategy intro 2" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/6cf19bfd-6bfe-4148-aac8-e9bc6f327962">

**Comment by philcockfield** [comment]
startupjourney.intro

<img width="1254" alt="Intro" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/98db5f16-c2ba-4e4b-bb3f-eef4a151121d">

**Comment by philcockfield** [comment]
startupjourney.2

0s, 36s
<img width="1699" alt="2a" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/92bfe94b-a63e-4bf4-8eb1-df87be2eb4c9">

12s
<img width="1186" alt="2b" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/b2df4a87-8bae-4589-a2cd-5a89cf9155bd">

**Comment by philcockfield** [comment]
startupjourney.3

0s
<img width="852" alt="3a" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/fd39d04a-effa-4d88-a43d-16560f676abb">


6s
<img width="1516" alt="3b" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/0fc4d6c6-0bc1-4d15-9fe0-18e46a3644e3">


40s
<img width="1326" alt="3c" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/310febee-fc1f-48e1-bfec-51fa05585dfc">

56s
<img width="1516" alt="3b" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/3b05f66f-8ac4-44be-a9f6-862862b05611">

**Comment by philcockfield** [comment]
startupjourney.4

<img width="1361" alt="4" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/bf798904-635a-44a9-a6d0-2ac9015e4f96">

**Comment by philcockfield** [comment]
startupjourney.5

0s
<img width="1760" alt="5a" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/d4b70a85-5486-4512-b89c-75debe92ca3d">


75s
<img width="979" alt="5b" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/f9171352-30b6-40f6-87bd-f43963aa85e5">

41s
<img width="979" alt="5c" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/62e3a768-68d5-406c-85e2-78f9e95eeb39">


51s
<img width="979" alt="5d" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/58242189-bd60-4789-9e71-94d6cad515af">

**Comment by philcockfield** [comment]
startupjourney5.eg

<img width="1760" alt="5a" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/d4b70a85-5486-4512-b89c-75debe92ca3d">

**Comment by philcockfield** [comment]
goodbm.intro

0s
<img width="1174" alt="Intro 1" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/01c9eb71-1325-4211-9b06-d12ba7e63fe7">

68s
<img width="1648" alt="Intro 2" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/6d478f21-f15d-4f5e-8a1d-dffdd11400ae">

**Comment by philcockfield** [comment]
goodbm.2.customermodel

0s
![2CustomerModel 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/22cb4a33-5321-4c6d-95ec-26b90a81eb70)


8s
<img width="1410" alt="2CustomerModel 2" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/d5ff0a7b-cbb9-45bf-9401-efc247e71ff6">

**Comment by philcockfield** [comment]
goodbm.3.impactmodel

0s
<img width="1648" alt="3ImpactModel 1" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/50ef5a31-5c5b-4973-9d20-7026ef348e87">


8s
<img width="1664" alt="3ImpactModel 2" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/213794cc-6087-4052-a9a0-96b9703ba645">

**Comment by philcockfield** [comment]
goodbm.4.economicmodel.intro

0s
![Overview 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/558d0b0f-3825-4e8f-b910-f9c2acd0d86b)


18s
![Overview 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/dc18622b-77d4-4cc2-bfc2-dccf339d817f)

**Comment by philcockfield** [comment]
goodbm.4.economicmodel.uniteconomics.1

0s
<img width="1463" alt="4EconomicModel UnitEconomics 1" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/3ab075d8-59cb-46f7-9da3-7ae26aa8251c">


15s
<img width="1546" alt="4EconomicModel UnitEconomics 2" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/578d9842-4c16-46b1-88fa-70e474373ced">

**Comment by philcockfield** [comment]
goodbm.4.economicmodel.uniteconomics.2

0s
<img width="1766" alt="4EconomicModel UnitEconomics 3" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/aba235d8-2008-4dff-ad3a-bba247be8702">

62s
<img width="1216" alt="4EconomicModel UnitEconomics 4" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/d9b84723-b9dd-4351-b67a-042dd4d86e05">

**Comment by philcockfield** [comment]
goodbm.4.economicmodel.growth

0s
![4EconomicModel Growth](https://github.com/cellplatform/platform-0.2.0/assets/185555/3b12ff14-e4f1-4f25-a190-76bc53e686bf)

4s
<img width="1408" alt="4EconomicModel Growth 1" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/170d388d-de31-4afe-bd70-f613352e6af8">

25s
<img width="1920" alt="4EconomicModel Growth 2" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/410b3c52-416a-41bb-9004-32297fad4296">

**Comment by philcockfield** [comment]
goodbm.conclusion

# no image?? 🐷

created new:

![goodbm conclusion](https://github.com/cellplatform/platform-0.2.0/assets/185555/38fbb2cb-c3d5-4f75-80c9-aeef0200a6ba)

**Comment by philcockfield** [comment]
goodbm.improve.jeff

0s
<img width="1298" alt="Intro" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/f8da0a30-2477-4d7f-aadf-ec2097d63b3f">


12s
<img width="1122" alt="Phone 1" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/170d2d17-5d56-494e-9ac4-68d5176de157">


55s
<img width="1388" alt="Phone 2" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/642cb060-c2db-413f-97ed-67ca0eb273e1">

**Comment by philcockfield** [comment]
goodbm.improve.leverage.intro

0s
<img width="1437" alt="Leverage Intro" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/9852d071-5eb1-44d4-b3ec-7ff3e386fb1a">

**Comment by philcockfield** [comment]
goodbm.improve.leverage.2types.intro

![Leverage Types](https://github.com/cellplatform/platform-0.2.0/assets/185555/506416bd-3e64-41d9-b85e-8315d2254daa)

**Comment by philcockfield** [comment]
goodbm.improve.leverage.2types.labour

![Leverage Types 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/ad03d995-eee1-486a-8f13-b8658cd81c5b)

**Comment by philcockfield** [comment]
goodbm.improve.leverage.2types.technology

![Leverage Types 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/a78a3bc6-fcd5-4cb0-b1d0-113f0d94ae74)

**Comment by philcockfield** [comment]
goodbm.improve.leverage.2types.capital
![Leverage Types 3](https://github.com/cellplatform/platform-0.2.0/assets/185555/d57fc9e2-bb59-4d2d-a646-3703493f79aa)

**Comment by philcockfield** [comment]
goodbm.improve.leverage.2types.Product
![Leverage Types 4](https://github.com/cellplatform/platform-0.2.0/assets/185555/273fabf7-4e97-4a4a-bae0-882ec8b5da47)

**Comment by philcockfield** [comment]
goodbm.improve.leverage.2types.media
![Leverage Types 5](https://github.com/cellplatform/platform-0.2.0/assets/185555/96195499-9f2c-4cc5-a618-1870d525defa)

**Comment by philcockfield** [comment]
goodbm.improve.leverage.2types.perceptual
![Leverage Types 6](https://github.com/cellplatform/platform-0.2.0/assets/185555/d1a76df8-a4e0-4482-9d9d-85f6cade59fe)

**Comment by philcockfield** [comment]
goodbm.improve.leverage.2types.network
![Leverage Types 7](https://github.com/cellplatform/platform-0.2.0/assets/185555/57184816-71bb-43df-b0dd-494327d72e57)

**Comment by philcockfield** [comment]
goodbm.improve.leverage.2types.strategic
![Leverage Types 8](https://github.com/cellplatform/platform-0.2.0/assets/185555/314e94b2-b9bc-4da9-9ac3-44763fd67ceb)

**Comment by philcockfield** [comment]
goodbm.improve.leverage.3size.1
![Size 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/6813f52a-01de-48bc-bcfe-49d7fcb79e81)

**Comment by philcockfield** [comment]
goodbm.improve.leverage.3size.2
![Size 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/7a99c045-65e0-4e0b-81a0-d2363b6cca39)

**Comment by philcockfield** [comment]
goodbm.improve.conclusion

![Conclusion](https://github.com/cellplatform/platform-0.2.0/assets/185555/f1a44a40-21fc-406a-94aa-7c330dd24ede)

**Comment by philcockfield** [comment]
strategy.stage.intro

![Intro](https://github.com/cellplatform/platform-0.2.0/assets/185555/52097361-322e-4bb2-a0e6-9f2b39aee9c9)

**Comment by philcockfield** [comment]
strategy.stage.1

![1](https://github.com/cellplatform/platform-0.2.0/assets/185555/036ae33e-47d0-4533-b08d-b0388484d5da)

**Comment by philcockfield** [comment]
strategy.stage.2

![2](https://github.com/cellplatform/platform-0.2.0/assets/185555/fa75631c-32ef-45f1-91dc-9370a67aaddf)

**Comment by philcockfield** [comment]
strategy.stage.3

![3](https://github.com/cellplatform/platform-0.2.0/assets/185555/3c37e55e-4aa1-45c5-9c74-78d01dc42962)

**Comment by philcockfield** [comment]
strategy.models.intro

<img width="844" alt="strategy models intro" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/0c36ff18-5adb-4ca7-84c6-679f024a6fc2">

**Comment by philcockfield** [comment]
strategy.models.2

0s
![strategy models 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/f2698344-9b96-46d7-8237-069d1cb9b3a8)


60s
<img width="1921" alt="3" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/e0a699f2-5782-4c40-ba5d-f77f803b7090">


67s
<img width="1921" alt="4" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/bd6b4125-498d-4a56-848e-1db0737a4fa1">


76s
<img width="1921" alt="5" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/ebd7d480-178e-4e5c-a9b1-6f98e19fd192">

**Comment by philcockfield** [comment]
strategy.models.validation

0s
![Validation 1](https://github.com/cellplatform/platform-0.2.0/assets/185555/883064dc-60be-44f3-b59e-430e66bb05f5)


21s
![Validation 2](https://github.com/cellplatform/platform-0.2.0/assets/185555/cdd6881b-539c-4ce2-8ad5-0026b5bede20)

**Comment by philcockfield** [comment]
strategy.models.together

![strategy models together](https://github.com/cellplatform/platform-0.2.0/assets/185555/070a44a1-3c7b-4415-a03d-2e641f526f9d)

**Comment by philcockfield** [comment]
strategy.timeline

<img width="1920" alt="strategy timeline" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/6c16ec25-0395-4629-a267-f7bb537656c0">

**Comment by philcockfield** [comment]
strategy.conclusion

<img width="1920" alt="strategy conclusion" src="https://github.com/cellplatform/platform-0.2.0/assets/185555/664939ab-6574-4aca-8d05-0901cab728fc">

**Comment by philcockfield** [comment]
Pitch

![pitching](https://github.com/cellplatform/platform-0.2.0/assets/185555/3d0a92fc-a173-4e2e-a7a9-b9608d8c0d27)

![example](https://github.com/cellplatform/platform-0.2.0/assets/185555/6cecd1ac-9e59-4512-8767-37cbe0e9ea86)

[structure.pdf](https://github.com/cellplatform/platform-0.2.0/files/12285608/structure.pdf)

![succes](https://github.com/cellplatform/platform-0.2.0/assets/185555/212918dc-b58a-4b9e-b448-ed221b4142f7)

![structure](https://github.com/cellplatform/platform-0.2.0/assets/185555/514453bd-a1fa-4463-bdc3-8ba853393400)

![thats-it](https://github.com/cellplatform/platform-0.2.0/assets/185555/4305ff3c-a432-4193-a1ba-fb1f3537af03)
